name: The mindfulness barn
favicon: null
layout_spectrum: 0.80295
typography_spectrum: 0.36719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3ebf1'
    - '#c2c2c2'
    - '#47423f'
    - '#25122c'
    - '#d2986d'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
