name: The mindfulness barn
favicon: null
layout_spectrum: 0.24913
typography_spectrum: 0.64323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7c5c6'
    - '#7a858a'
    - '#000700'
    - '#007f77'
    - '#00c39a'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
